### ISSUE TITLE
fusion router go brrrrrrrrrrrrrrr

### ISSUE THREAD

**Issue by sk7725** [deltanedas/routorio-old#5]
6.0

rhino.EvaluatorException: Java class "mindustry.world.blocks.liquid.LiquidRouter" has no public instance field or method named "LiquidRouterBuild". (fusion-router#170)
	at rhino.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:68)
	at rhino.Context.reportRuntimeError(Context.java:830)
	at rhino.Context.reportRuntimeError(Context.java:876)
	at rhino.Context.reportRuntimeError2(Context.java:850)
	at rhino.JavaMembers.reportMemberNotFound(JavaMembers.java:805)
	at rhino.NativeJavaClass.get(NativeJavaClass.java:91)
	at rhino.ScriptableObject.getProperty(ScriptableObject.java:2182)
	at rhino.ScriptRuntime.getObjectProp(ScriptRuntime.java:1512)
	at rhino.ScriptRuntime.getObjectProp(ScriptRuntime.java:1506)
	at rhino.gen.fusion_router_20._c_anonymous_12(fusion-router:170)
	at rhino.gen.fusion_router_20.call(fusion-router)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:346)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3338)
	at rhino.gen.fusion_router_20.call(fusion-router)
	at rhino.ArrowFunction.call(ArrowFunction.java:33)
	at rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:141)
	at rhino.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:92)
	at rhino.Context.call(Context.java:524)
	at rhino.ContextFactory.call(ContextFactory.java:446)
	at rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:92)
	at rhino.jdk18.VMBridge_jdk18.lambda$newInterfaceProxy$0(VMBridge_jdk18.java:100)
	at com.sun.proxy.$Proxy2.get(Unknown Source)
	at mindustry.world.Block.newEntity(Block.java:496)
	at mindustry.world.Tile.changeEntity(Tile.java:553)
	at mindustry.world.Tile.setBlock(Tile.java:191)
	at mindustry.world.Tile.setBlock(Tile.java:179)
	at mindustry.world.blocks.BuildBlock.constructFinish(BuildBlock.java:63)
	at mindustry.gen.Call.constructFinish(Call.java:242)
	at mindustry.world.blocks.BuildBlock.constructed(BuildBlock.java:99)
	at mindustry.world.blocks.BuildBlock$BuildEntity.construct(BuildBlock.java:217)
	at mindustry.gen.BuilderMinerUnit.update(BuilderMinerUnit.java:955)
	at mindustry.entities.EntityGroup.each(EntityGroup.java:66)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:57)
	at mindustry.gen.Groups.update(Groups.java:52)
	at mindustry.core.Logic.update(Logic.java:377)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:151)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:170)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

**Comment by deltanedas** [comment]
ok

**Comment by USMP-lancer** [comment]
same
