### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by sk7725** [deltanedas/routorio-old#8]
Mindustry has crashed. How unfortunate.
Version: bleeding-edge build 10313
OS: Windows 10 x64
Java Version: 14.0.2
Java Architecture: 64
6 Mods: modding-toolbox:3.6.0, routorio:2.30.1, substructure:0.1, testers:0.16, ui-lib:2.15.8, unit-factory:2.2.0

java.lang.NullPointerException
	at arc.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:132)
	at arc.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:51)
	at mindustry.graphics.LoadRenderer.draw(LoadRenderer.java:226)
	at mindustry.ClientLauncher.update(ClientLauncher.java:133)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:170)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

**Comment by sk7725** [comment]
Works without crash when I removed routorio.

**Comment by deltanedas** [comment]
i cant imagine how routorio could break the loading screen especially since it womm, update mindustry and provide last_log.txt

**Comment by deltanedas** [comment]
inactivity

**Comment by sk7725** [comment]
Sorry, I forgot. And also, I guess sk7725/testers fused with routorio, making it crash.
